[[headers]]
 for = "/*"
[headers.values]
 X-Frame-Options = "SAMEORIGIN"
 X-XSS-Protection = "1; mode=block"
 X-Content-Type-Options = "nosniff"
 Content-Security-Policy = "default-src 'none'; script-src 'self' www.googletagmanager.com www.google-analytics.com; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'"
