[[headers]]
 for = "/*"
[headers.values]
 X-Frame-Options = "SAMEORIGIN"
 X-XSS-Protection: 1; mode=block
 X-Content-Type-Options = "nosniff"
 Content-Security-Policy : "default-src 'none';"     
 Content-Security-Policy : "style-src 'self';"
 Content-Security-Policy : "form-action 'self';"
 Content-Security-Policy : "script-src 'self';"
 Content-Security-Policy : "connect-src 'self';"
 Content-Security-Policy : "img-src 'self';"
 Content-Security-Policy : "base-uri 'self';"
