[[headers]]
 for = "/*"
[headers.values]
 X-Frame-Options = "SAMEORIGIN"
 X-XSS-Protection = "1; mode=block"
 X-Content-Type-Options = "nosniff"
 Content-Security-Policy = "default-src 'self'; script-src self'  https://www.googletagmanager.com; style-src ''unsafe-inline';"
